package com.bdtx.mod_network.Constant

const val WEBSOCKET_URL = "wss://back.monitor.beidou.online/ws"
//const val BASE_URL = "http://back.tdwtv2.pg8.ink"
const val BASE_URL = "https://back.monitor.beidou.online"
const val ACCOUNT_PWD_LOGIN = "/api/monitor/app-users/login/pwd"
const val CODE_LOGIN = "/api/monitor/app-users/login/code"
const val TOKEN_LOGIN = "/api/monitor/app-users/login/token"
const val WX_LOGIN = "/api/monitor/app-users/login/wx-applet"
const val PWD_UPDATE = "/api/monitor/app-users/pwd"
const val BIND_DEVICE = "/api/monitor/app-users/app/bind/addr"
const val BIND_DEVICE_BY_SN = "/api/monitor/app-users/app/bind/sn"
const val DEVICE_LIST = "/api/monitor/app-users/app/terminals"
const val UNBIND_DEVICE = "/api/monitor/app-users/unbind/addr"
const val SEND_PHONE_CODE = "/api/monitor/ver-codes/login"
const val DOWN_FILE = "/api/monitor/files/"
const val GET_USER_INFO = "/api/monitor/app-users/info"
const val LIVE_ROOMS = "/api/monitor/live-broadcast/rooms"
const val CREATE_ROOMS = "/api/monitor/live-broadcast/room"
const val GET_ROOM_INFO = "/api/monitor/live-broadcast/room"
const val WAREHOUSING = "/api/admin/inventory"
const val GET_DEVICE_TYPE = "/api/admin/enums/terminal-types"
const val GET_USAGE_TYPE = "/api/admin/enums/terminal-use-scopes"